# Generated by Django 5.0.14 on 2025-07-06 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mealbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentuser'),
        ),
    ]
