# Generated by Django 5.0.14 on 2025-07-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mealslot_alter_specialorder_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookingrecord',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='bookingrecord',
            name='qr_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookingrecord',
            name='status',
            field=models.CharField(default='Booked', max_length=20),
        ),
    ]
