# Generated by Django 5.0.14 on 2025-07-26 04:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_default_mealslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrecord',
            name='is_special_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='bookingrecord',
            unique_together={('user', 'meal_type', 'date', 'is_special_order')},
        ),
        migrations.CreateModel(
            name='SpecialOrderSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('max_slots', models.PositiveIntegerField(default=25)),
                ('available_slots', models.PositiveIntegerField(default=25)),
                ('is_active', models.BooleanField(default=True)),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mealslot')),
            ],
            options={
                'unique_together': {('meal_type', 'date')},
            },
        ),
    ]
