# Generated by Django 5.0.14 on 2025-07-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_bookingrecord_is_special_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialorderslot',
            name='available_slots',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='specialorderslot',
            name='max_slots',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
