# Generated by Django 5.0.14 on 2025-07-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_specialorderslot_available_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialorderslot',
            name='available_slots',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='specialorderslot',
            name='max_slots',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterUniqueTogether(
            name='bookingrecord',
            unique_together={('user', 'meal_type', 'date', 'is_special_order', 'status')},
        ),
    ]
